trigger:
- develop

stages:
- template: ../../.azure/templates/build-template.yml
  parameters:
    serviceName: loanflow
    dockerfilePath: Dockerfile
    imageRepository: loanflow-dev

- template: ../../.azure/templates/deploy-template.yml
  parameters:
    environment: dev
    namespace: dev
    helmChartPath: helm/loanflow