trigger:
- main

variables:
  imageRepository: loanflow-app

stages:

# Build Stage
- template: ../templates/build-template.yml
  parameters:
    serviceName: loanflow
    dockerfilePath: Dockerfile
    imageRepository: $(imageRepository)

# Deploy to DEV
- template: ../templates/deploy-template.yml
  parameters:
    environment: dev
    namespace: dev
    helmChartPath: helm/loanflow

# Approval for PROD
- template: ../templates/approval-gate.yml
  parameters:
    environment: prod

# Deploy to PROD
- template: ../templates/deploy-template.yml
  parameters:
    environment: prod
    namespace: prod
    helmChartPath: helm/loanflow