trigger: none

stages:
- template: ../../.azure/templates/approval-gate.yml
  parameters:
    environment: preprod

- template: ../../.azure/templates/deploy-template.yml
  parameters:
    environment: preprod
    namespace: preprod
    helmChartPath: helm/loanflow