trigger: none

stages:
- template: ../../.azure/templates/approval-gate.yml
  parameters:
    environment: uat

- template: ../../.azure/templates/deploy-template.yml
  parameters:
    environment: uat
    namespace: uat
    helmChartPath: helm/loanflow