trigger: none

stages:

- template: ../../.azure/templates/approval-gate.yml
  parameters:
    environment: prod

- template: ../../.azure/templates/deploy-template.yml
  parameters:
    environment: prod
    namespace: prod
    helmChartPath: helm/loanflow