parameters:
  environment: ''
  namespace: ''
  helmChartPath: ''

stages:
- stage: Deploy_${{ parameters.environment }}
  displayName: Deploy to ${{ parameters.environment }}

  jobs:
  - deployment: Deploy_App
    environment: ${{ parameters.environment }}

    strategy:
      runOnce:
        deploy:
          steps:

          - task: HelmDeploy@0
            displayName: Helm Upgrade
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'AKS-Service-Connection'
              namespace: ${{ parameters.namespace }}
              command: upgrade
              chartType: FilePath
              chartPath: ${{ parameters.helmChartPath }}
              releaseName: loanflow
              overrideValues: |
                image.tag=$(Build.BuildId)